---
title: "Hamming Distance Calculations"
output: github_document
---

Setup environment  

```{r}
library(tidyverse)
library(bioseq)
library(DNABarcodes)
library(pheatmap)
library(viridis)
```

Hamming Distance of I7 Nextera indexes to I7 NextFlex 289:384 indexes  

```{r}
Nextera_I7_Primers <- read_csv("../barcodes/Nextera_i7_Adapters.csv") %>%
  rename(Index_ID = 1, I7_Index = 2)
Nextera_I5_Primers <- read_csv("../barcodes/Nextera_i5_Adapters.csv") %>%
  rename(Index_ID = 1, I5_Index = 2)
NextFlex <- read_csv("../barcodes/NEXTFLEX_Adapters.csv") %>%
  rename(Index_ID = 1, I7_Index = 2, I5_Index = 3)

I7_Merged <-
  bind_rows(
  Nextera_I7_Primers %>% select(Index_ID, I7_Index),
  NextFlex %>% slice(289:384) %>% select(Index_ID, I7_Index)
)

tmp <- barcode.set.distances(pull(I7_Merged, I7_Index), metric = c("hamming"))
rownames(tmp) <- I7_Merged$Index_ID
colnames(tmp) <- I7_Merged$Index_ID
x1 <- tmp@x
nameX <- tmp@Dimnames
nameY <- tmp@Dimnames
tmp <- as.matrix(tmp, row.names = tmp@Dimnames)
tmp <- as.data.frame(tmp)
tmp <- tmp %>% rownames_to_column(., var = "rowname") %>% as_tibble()
tmp2 <- tmp %>% pivot_longer(cols = -1, names_to = "barcode", values_to = "hamming")

tmp <- barcode.set.distances(pull(I7_Merged, I7_Index), metric = c("seqlev"))
rownames(tmp) <- I7_Merged$Index_ID
colnames(tmp) <- I7_Merged$Index_ID
x1 <- tmp@x
nameX <- tmp@Dimnames
nameY <- tmp@Dimnames
tmp <- as.matrix(tmp, row.names = tmp@Dimnames)
tmp <- as.data.frame(tmp)
tmp <- tmp %>% rownames_to_column(., var = "rowname") %>% as_tibble()
tmp <- tmp %>% pivot_longer(cols = -1, names_to = "barcode", values_to = "seqlev")

i7 <- full_join(tmp, tmp2)

i7 %>% sample_frac(size = 1, replace = FALSE) %>% 
  filter(str_detect(rowname, "UDI")) %>%
  filter(str_detect(barcode, "v2")) %>%
  rename(NEXTFLEX_ID = 1, Nextera_i7 = 2) %>%
  write_csv("../indexDistances/i7_distances.csv")

i7_tmp <-
  i7 %>% sample_frac(size = 1, replace = FALSE) %>% 
  filter(str_detect(rowname, "UDI")) %>%
  filter(str_detect(barcode, "v2")) %>%
  select(-seqlev) %>%
  filter(hamming > 2) %>%
  pivot_wider(names_from = barcode, values_from = hamming) %>%
  arrange(rowname) %>%
  column_to_rownames(var = "rowname")

pheatmap(
  i7_tmp,
  cluster_rows = T,
  cluster_cols = T,
  fontsize = 10,
  fontsize_row = 6,
  fontsize_col = 6,
  border_color = NA,
  color = viridis(
    n = 6,
    direction = -1,
    option = "rocket",
    end = 0.8
  ),
  clustering_method = "ward.D",
  na_col = "white",
  main = "I7 barcode Hamming distances, Hamming > 2",
  filename = "../plots/i7_hamming_greater2.pdf",
  width = 10,
  height = 7.5
)

pheatmap(
  i7_tmp,
  cluster_rows = F,
  cluster_cols = F,
  fontsize = 10,
  fontsize_row = 6,
  fontsize_col = 6,
  border_color = NA,
  color = viridis(
    n = 6,
    direction = -1,
    option = "rocket",
    end = 0.8
  ),
  na_col = "white",
  main = "I7 barcode Hamming distances, Hamming > 2",
  filename = "../plots/i7_hamming_greater2_unclustered.pdf",
  width = 10,
  height = 7.5
)

pheatmap(
  i7_tmp,
  cluster_rows = T,
  cluster_cols = T,
  fontsize = 10,
  fontsize_row = 6,
  fontsize_col = 6,
  border_color = NA,
  color = viridis(
    n = 6,
    direction = -1,
    option = "rocket",
    end = 0.8
  ),
  clustering_method = "ward.D",
  na_col = "white",
  main = "I7 barcode Hamming distances, Hamming > 2",
  filename = "../plots/i7_hamming_greater2.png",
  width = 10,
  height = 7.5
)

pheatmap(
  i7_tmp,
  cluster_rows = F,
  cluster_cols = F,
  fontsize = 10,
  fontsize_row = 6,
  fontsize_col = 6,
  border_color = NA,
  color = viridis(
    n = 6,
    direction = -1,
    option = "rocket",
    end = 0.8
  ),
  na_col = "white",
  main = "I7 barcode Hamming distances, Hamming > 2",
  filename = "../plots/i7_hamming_greater2_unclustered.png",
  width = 10,
  height = 7.5
)
```

Compare Hamming Distance of I5 Nextera indexes to I5 NextFlex 289:384 indexes  

```{r}
I5_Merged <-
  bind_rows(
  Nextera_I5_Primers %>% select(Index_ID, I5_Index),
  NextFlex %>% slice(289:384) %>% select(Index_ID, I5_Index)
)

tmp <- barcode.set.distances(pull(I5_Merged, I5_Index), metric = c("hamming"))
rownames(tmp) <- I5_Merged$Index_ID
colnames(tmp) <- I5_Merged$Index_ID
x1 <- tmp@x
nameX <- tmp@Dimnames
nameY <- tmp@Dimnames
tmp <- as.matrix(tmp, row.names = tmp@Dimnames)
tmp <- as.data.frame(tmp)
tmp <- tmp %>% rownames_to_column(., var = "rowname") %>% as_tibble()
tmp2 <- tmp %>% pivot_longer(cols = -1, names_to = "barcode", values_to = "hamming")

tmp <- barcode.set.distances(pull(I5_Merged, I5_Index), metric = c("seqlev"))
rownames(tmp) <- I5_Merged$Index_ID
colnames(tmp) <- I5_Merged$Index_ID
x1 <- tmp@x
nameX <- tmp@Dimnames
nameY <- tmp@Dimnames
tmp <- as.matrix(tmp, row.names = tmp@Dimnames)
tmp <- as.data.frame(tmp)
tmp <- tmp %>% rownames_to_column(., var = "rowname") %>% as_tibble()
tmp <- tmp %>% pivot_longer(cols = -1, names_to = "barcode", values_to = "seqlev")

i5 <- full_join(tmp, tmp2)

i5 %>%
  filter(str_detect(rowname, "UDI")) %>%
  filter(str_detect(barcode, "v2")) %>%
  rename(NEXTFLEX_ID = 1, Nextera_i5 = 2) %>%
  write_csv("../indexDistances/i5_distances.csv")

i5_tmp <-
  i5 %>%
  filter(str_detect(rowname, "UDI")) %>%
  filter(str_detect(barcode, "v2")) %>%
  select(-seqlev) %>%
  filter(hamming > 2) %>%
  pivot_wider(names_from = barcode, values_from = hamming) %>%
  arrange(rowname) %>%
  column_to_rownames(var = "rowname")

pheatmap(
  i5_tmp,
  cluster_rows = T,
  cluster_cols = T,
  fontsize = 10,
  fontsize_row = 6,
  fontsize_col = 6,
  border_color = NA,
  color = viridis(
    n = 6,
    direction = -1,
    option = "rocket",
    end = 0.8
  ),
  clustering_method = "ward.D",
  na_col = "white",
  main = "I5 barcode Hamming distances, Hamming > 2",
  filename = "../plots/i5_hamming_greater2.pdf",
  width = 10,
  height = 7.5
)

pheatmap(
  i5_tmp,
  cluster_rows = F,
  cluster_cols = F,
  fontsize = 10,
  fontsize_row = 6,
  fontsize_col = 6,
  border_color = NA,
  color = viridis(
    n = 6,
    direction = -1,
    option = "rocket",
    end = 0.8
  ),
  na_col = "white",
  main = "I5 barcode Hamming distances, Hamming > 2",
  filename = "../plots/i5_hamming_greater2_unclustered.pdf",
  width = 10,
  height = 7.5
)

pheatmap(
  i5_tmp,
  cluster_rows = T,
  cluster_cols = T,
  fontsize = 10,
  fontsize_row = 6,
  fontsize_col = 6,
  border_color = NA,
  color = viridis(
    n = 6,
    direction = -1,
    option = "rocket",
    end = 0.8
  ),
  clustering_method = "ward.D",
  na_col = "white",
  main = "I5 barcode Hamming distances, Hamming > 2",
  filename = "../plots/i5_hamming_greater2.png",
  width = 10,
  height = 7.5
)

pheatmap(
  i5_tmp,
  cluster_rows = F,
  cluster_cols = F,
  fontsize = 10,
  fontsize_row = 6,
  fontsize_col = 6,
  border_color = NA,
  color = viridis(
    n = 6,
    direction = -1,
    option = "rocket",
    end = 0.8
  ),
  na_col = "white",
  main = "I5 barcode Hamming distances, Hamming > 2",
  filename = "../plots/i5_hamming_greater2_unclustered.png",
  width = 10,
  height = 7.5
)
```

## Finished!